# -*- coding: utf-8 -*-
"""gradients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLFsqoXtPO5GLCntJTLeGiCwof_DVsIl
"""

import torch
from transformers import set_seed
set_seed(2390)


def final(foo, upsample, alpha=1.0):
    # ----- hard assignment (exactly your current behavior) -----
    bar_hard = (foo == 0).float()
    dim = 2 if upsample else 1
    bar_hard = bar_hard / (bar_hard.sum(dim=dim, keepdim=True) + 1e-9)

    # ----- soft assignment (for gradients) -----
    # weights highest when foo is near 0
    bar_soft = torch.softmax(-alpha * foo.abs(), dim=dim)

    # ----- straight-through combine: hard forward, soft backward -----
    bar = bar_hard + (bar_soft - bar_soft.detach())
    print(f"{bar=}")
    return bar

def common(boundaries, upsample=False):
    boundaries = boundaries.clone()

    n_segments = boundaries.sum(dim=-1).max().item()
    print(f"{n_segments=}")

    if upsample:
        n_segments += 1

    if n_segments == 0:
        return None

    tmp = torch.zeros_like(
        boundaries
    ).unsqueeze(2) + torch.arange(
        start=0,
        end=n_segments,
        device=boundaries.device
    )
    print(f"{tmp=}")

    hh1 = boundaries.cumsum(1)

    print(f"{hh1=}")

    if not upsample:
        hh1 -= boundaries #  i.e a tesnor that counts from 0 to n_segments is reduce by either 1 or 0
    print(f"{hh1=}")
    foo = tmp - hh1.unsqueeze(-1)
    print(f"{foo=}")
    return foo


def downsample(boundaries, hidden, null_group):
    """
        Downsampling

        - The first element of boundaries tensor is always 0 and doesn't matter
        - 1 starts a new group
        - We append an extra "null" group at the beginning
        - We discard last group because it won't be used (in terms of upsampling)

        Input:
            boundaries: B x L
            hidden: L x B x D
        Output:
            shortened_hidden: S x B x D
    """

    foo = common(boundaries, upsample=False)  # B x L x S

    if foo is None:
        return null_group.repeat(1, hidden.size(1), 1)
    else:
        bar = final(foo=foo, upsample=False)  # B x L x S

        shortened_hidden = torch.einsum('lbd,bls->sbd', hidden, bar)
        shortened_hidden = torch.cat(
            [null_group.repeat(1, hidden.size(1), 1), shortened_hidden], dim=0
        )
        return shortened_hidden, foo, bar

# ----------------------------
# Debug setup
# ----------------------------

B, L, D = 1, 10, 2

# Hard boundary pattern: 1 ends token
# tokens: [0,1,2] [3,4,5]
b_hard = torch.tensor([[0., 1., 0., 0., 0., 1., 0 , 1, 0, 1]])

# Trainable logits
logits = torch.tensor(
    [[-2.0, 2.0, -2.0, -2.0, -2.0,  2.0, -2.0, 2.0, -2.0, 2.0]],
    requires_grad=True
)

# Probabilities
p = torch.sigmoid(logits)

# STE boundaries
boundaries = b_hard + (p - p.detach())

# Dummy hidden states
hidden = torch.arange(L * B * D).float().reshape(L, B, D) / 10.0
null_group = torch.zeros(1, 1, D)

# ----------------------------
# Forward pass
# ----------------------------

shortened, foo, bar = downsample(boundaries, hidden, null_group)

print("\n=== INPUTS ===")
print("logits:", logits.detach())
print("p (sigmoid):", p.detach())
print("boundaries (STE, forward):", boundaries.detach())

print("\n=== foo (segment offsets) ===")
print(foo[0])

print("\n=== bar (assignment weights) ===")
print(bar[0])

print("\n=== hidden ===")
print(hidden[:, 0, :])

print("\n=== shortened tokens (with null) ===")
print(shortened[:, 0, :])

# ----------------------------
# Backward pass
# ----------------------------

loss = shortened.sum()
loss.backward()

print("\n=== GRADIENTS ===")
print("grad logits:", logits.grad)

# Bucket gradients by boundary value
g = logits.grad[0].abs()
bh = b_hard[0]

print("\nMean |grad| where boundary == 1:", g[bh == 1].mean().item())
print("Mean |grad| where boundary == 0:", g[bh == 0].mean().item())

print("\nMean |grad| where boundary == 1:", g[bh == 1])
print("Mean |grad| where boundary == 0:", g[bh == 0])


